import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "../components/Nav/navbar";
import Footer from "../components/Footer/footer";
import { AuthProvider } from "@/context/AuthContext";

const siliguri = Hind_Siliguri({
	subsets: ["bengali"],
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Learn With Hemel",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${siliguri.className} overflow-y-scroll`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AuthProvider>
						<Navbar />
						{children}
						<Footer />
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
